version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: nestjs-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
